AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Daily Newsletter Summarizer - Fetches newsletters, summarizes with Claude, emails digest

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: python3.11

Parameters:
  ScheduleExpression:
    Type: String
    Default: "cron(0 14 * * ? *)"  # 7am PT (14:00 UTC)
    Description: Cron expression for when to run (UTC timezone)

Resources:
  NewsletterSummarizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: newsletter-summarizer
      CodeUri: .
      Handler: src.handler.lambda_handler
      Description: Fetches daily newsletters and sends summarized digest
      Environment:
        Variables:
          USE_LOCAL_CONFIG: "false"
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:newsletter-summarizer/*"
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Description: Trigger newsletter summarizer daily
            Enabled: true

  # CloudWatch Log Group with retention
  NewsletterSummarizerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${NewsletterSummarizerFunction}"
      RetentionInDays: 14

Outputs:
  FunctionArn:
    Description: Newsletter Summarizer Lambda Function ARN
    Value: !GetAtt NewsletterSummarizerFunction.Arn

  FunctionName:
    Description: Newsletter Summarizer Lambda Function Name
    Value: !Ref NewsletterSummarizerFunction
